### ISSUE TITLE
italian strings

### ISSUE THREAD

**Issue by zemaree** [Kvalyr/KayrCovenantMissions#3]
-- Italian
stringTable["itIT"] = {}
stringTable["itIT"]["_adviceFrameWidth"] = 550
stringTable["itIT"]["_adviceFrameHeight"] = 100
stringTable["itIT"]["Add some units to your team to begin success estimation."] = "Aggiungi qualche unità al tuo gruppo per iniziare la stima del successo"
stringTable["itIT"]["round"] = "turno"
stringTable["itIT"]["rounds"] = "turni"
stringTable["itIT"]["It would take"] = "Servirebbero"
stringTable["itIT"]["combat"] = "combattimento"
stringTable["itIT"]["for your current team to beat the enemy team."] = "per il tuo gruppo per battere il gruppo avversario"
stringTable["itIT"]["for the enemy team to beat your current team."] = "per il gruppo avversario per sconfiggere il tuo gruppo"
stringTable["itIT"]["Success is possible with your current units, but it will be close."] = "E' possibile vincere con il tuo gruppo, ma il margine è ridotto"
stringTable["itIT"]["There is a reasonable chance of success with your current units."] = "C'è un ragionevole margine di successo per il tuo gruppo"
stringTable["itIT"]["Mission success is impossible with your current units."] = "E' impossibile vincere con tuo gruppo"
stringTable["itIT"]["Warning: This guidance is a rough estimate. Unit abilities strongly influence the actual result."] = "Attenzione: Queste stime sono una approssimazione. Le abilità delle unità influenzano fortemente il risultato attuale"
stringTable["itIT"]["[No Mission Selected]"] = "[Nessuna missione selezionata]"

**Comment by zemaree** [comment]
I checked in game and it give weird result due to the phrase construction in italian and the fact that vers change from singular to plurals.

It would take 1 combat round became "Servirebbe 1 turno di combattimento"
It would take 2 combat rounds became "Servirebbero 2 turni di combattimento"

as you can see you should add 2 it would take and "combat round" and "combat rounds" as complete string otherwise you get in italian:

combat round = "di combattimento turno" (should be "turno di combattimento" -> (swapped words)) or simply remove combat (cause it's clear that we are talking about combat round) and you shorten the string for the small video.

stringTable["itIT"]["combat"] = ""

There is no work around for It would take (1 or more) round(s) have to be different (I put the 1+ string cause I think that it's really unwilling that you have 1 ar turn number)

**Comment by Kvalyr** [comment]
Thanks for this. I'll implement your translation soon. Your suggestions around the construction of the sentences are also already in the works (these issues came up with other locales too) - I just haven't gotten around to implementing it cleanly yet.
